/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was generated by "go run gen/main.go -mode test > gen_test.go". Do not edit
// directly.

package cloud

import (
	"testing"

	"github.com/bowei/gce-gen/pkg/cloud"
	"github.com/bowei/gce-gen/pkg/cloud/filter"
)

func TestGAAddresses(t *testing.T) {
}
func TestAlphaAddresses(t *testing.T) {
}
func TestBetaAddresses(t *testing.T) {
}
func TestGAGlobalAddresses(t *testing.T) {
}
func TestGABackendServices(t *testing.T) {
}
func TestAlphaBackendServices(t *testing.T) {
}
func TestAlphaRegionBackendServices(t *testing.T) {
}
func TestGADisks(t *testing.T) {
}
func TestAlphaDisks(t *testing.T) {
}
func TestAlphaRegionDisks(t *testing.T) {
}
func TestGAFirewalls(t *testing.T) {
}
func TestGAForwardingRules(t *testing.T) {
}
func TestAlphaForwardingRules(t *testing.T) {
}
func TestGAGlobalForwardingRules(t *testing.T) {
}
func TestGAHealthChecks(t *testing.T) {
}
func TestAlphaHealthChecks(t *testing.T) {
}
func TestGAHttpHealthChecks(t *testing.T) {
}
func TestGAHttpsHealthChecks(t *testing.T) {
}
func TestGAInstanceGroups(t *testing.T) {
}
func TestGAInstances(t *testing.T) {
}
func TestBetaInstances(t *testing.T) {
}
func TestAlphaInstances(t *testing.T) {
}
func TestAlphaNetworkEndpointGroups(t *testing.T) {
}
func TestGAProjects(t *testing.T) {
}
func TestGARegions(t *testing.T) {
}
func TestGARoutes(t *testing.T) {
}
func TestGASslCertificates(t *testing.T) {
}
func TestGATargetHttpProxies(t *testing.T) {
}
func TestGATargetHttpsProxies(t *testing.T) {
}
func TestGATargetPools(t *testing.T) {
}
func TestGAUrlMaps(t *testing.T) {
}
func TestGAZones(t *testing.T) {
}
